In [4]:
import pandas as pd

df = pd.read_csv("../data/student_performance.csv")

print(df.head())
print("\nDataset Shape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

   Student_ID    Name Gender  Age  Study_Hours  Attendance  Assignments  \
0           1     Ali      M   16            5          90            9
1           2   Ahmed      M   15            3          70            6
2           3    Sara      F   16            7          95           10
3           4  Fatima      F   15            6          92            9
4           5   Usman      M   16            2          65            5

   Midterm  Previous_Score  Final
0       75              72     80
1       55              60     58
2       88              85     92
3       82              80     87
4       48              52     50

Dataset Shape:
(15, 10)

Columns:
Index(['Student_ID', 'Name', 'Gender', 'Age', 'Study_Hours', 'Attendance',
       'Assignments', 'Midterm', 'Previous_Score', 'Final'],
      dtype='object')

In [7]:
df.tail()#printing last 5 rows
#index starts at 0

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Assignments,Midterm,Previous_Score,Final
10,11,Hina,F,16,6,88,8,78,75,82
11,12,Hamza,M,15,5,85,8,72,70,76
12,13,Noor,F,16,7,93,9,86,84,89
13,14,Daniyal,M,15,2,60,5,50,48,52
14,15,Eman,F,16,8,97,10,90,91,94

In [13]:
#Total number of students
print(f"Total number of students:{len(df)}")

Total number of students:15

In [16]:
#Average final marks
print(f"Average final marks: {df["Final"].mean():.2f}")

Average final marks: 75.47

In [18]:
#Highest final marks
print(f"Highest final marks: {df["Final"].max():.2f}")

Highest final marks: 98.00

In [19]:
#Lowest final marks
print(f"Lowest final marks: {df["Final"].min():.2f}")

Lowest final marks: 42.00

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      15 non-null     int64
 1   Name            15 non-null     object
 2   Gender          15 non-null     object
 3   Age             15 non-null     int64
 4   Study_Hours     15 non-null     int64
 5   Attendance      15 non-null     int64
 6   Assignments     15 non-null     int64
 7   Midterm         15 non-null     int64
 8   Previous_Score  15 non-null     int64
 9   Final           15 non-null     int64
dtypes: int64(8), object(2)
memory usage: 1.3+ KB

In [21]:
df.describe()

,Student_ID,Age,Study_Hours,Attendance,Assignments,Midterm,Previous_Score,Final
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,8.000000,15.533333,5.066667,82.800000,7.733333,71.600000,71.733333,75.466667
std,4.472136,0.516398,2.491892,14.536653,2.086236,17.859771,15.863105,18.188955
min,1.000000,15.000000,1.000000,55.000000,4.000000,40.000000,45.000000,42.000000
25%,4.500000,15.000000,3.000000,72.500000,6.000000,56.500000,61.000000,61.500000
50%,8.000000,16.000000,5.000000,88.000000,8.000000,75.000000,72.000000,80.000000
75%,11.500000,16.000000,7.000000,94.000000,9.500000,87.000000,84.500000,90.500000
max,15.000000,16.000000,9.000000,99.000000,10.000000,95.000000,94.000000,98.000000

In [23]:
#Checking the missing values
df.isnull().sum()

Student_ID        0
Name              0
Gender            0
Age               0
Study_Hours       0
Attendance        0
Assignments       0
Midterm           0
Previous_Score    0
Final             0
dtype: int64

In [27]:
#Check Duplicate rows
print(f"Duplicate row in data frame= {df.duplicated().sum()}")

Duplicate row in data frame= 0

In [35]:
#Students at risk
df[df['Final'] < 50]

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Assignments,Midterm,Previous_Score,Final
9,10,Hassan,M,15,1,55,4,40,45,42